---
title: "Hw6"
author: "Xiaoyu Lian (A17025943)"
format: pdf
editor: visual
---

## HW 6
Can you improve this analysis code?

```{r}
library(bio3d)
s1 <- read.pdb("4AKE") # kinase with drug
s2 <- read.pdb("1AKE") # kinase no drug
s3 <- read.pdb("1E4Y") # kinase with drug
s1.chainA <- trim.pdb(s1, chain="A", elety="CA")
s2.chainA <- trim.pdb(s2, chain="A", elety="CA")
s3.chainA <- trim.pdb(s3, chain="A", elety="CA")
s1.b <- s1.chainA$atom$b
s2.b <- s2.chainA$atom$b
s3.b <- s3.chainA$atom$b
plotb3(s1.b, sse=s1.chainA, typ="l", ylab="Bfactor")
plotb3(s2.b, sse=s2.chainA, typ="l", ylab="Bfactor")
plotb3(s3.b, sse=s3.chainA, typ="l", ylab="Bfactor")
```

Step 1
```{r}
# x <- read.pdb('name')
```
Step 2
```{r}
# x.chainA <- trim.pdb(x, chain = "A", elety = "CA")
```
step 3
```{r}
# x.b <- x.chainA$atom$b
```
step 4
```{r}
# plotx(x.b, sse=x.chainA, typ="l", ylab="Bfactor")
```
combine
```{r}
plotfunc <- function(name){
  x.chainA <- trim.pdb(read.pdb(name), chain = "A", elety = "CA")
  x.b <- x.chainA$atom$b
  plotx <- plotb3(x.b, sse=x.chainA, typ="l", ylab="Bfactor")
  return(plotx)}
```

```{r}
plotfunc("4AKE")
plotfunc("1AKE")
plotfunc("1E4Y")
```

